version: "3"

services:
  db:
    container_name: bagaig-db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./:/tmp/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

